# Generated by Django 2.0.3 on 2018-03-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_motivation'),
        ('backend', '0004_subreddit'),
    ]

    operations = [
    ]
